// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countSessionMessages = `-- name: CountSessionMessages :one
SELECT COUNT(*) FROM messages WHERE session_id = ?
`

func (q *Queries) CountSessionMessages(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSessionMessages, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (id, session_id, role, parts, model, provider, is_summary, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, session_id, role, parts, model, provider, is_summary, created_at, updated_at
`

type CreateMessageParams struct {
	ID        string         `json:"id"`
	SessionID string         `json:"session_id"`
	Role      string         `json:"role"`
	Parts     string         `json:"parts"`
	Model     sql.NullString `json:"model"`
	Provider  sql.NullString `json:"provider"`
	IsSummary int64          `json:"is_summary"`
	CreatedAt int64          `json:"created_at"`
	UpdatedAt int64          `json:"updated_at"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.ID,
		arg.SessionID,
		arg.Role,
		arg.Parts,
		arg.Model,
		arg.Provider,
		arg.IsSummary,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Parts,
		&i.Model,
		&i.Provider,
		&i.IsSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages WHERE id = ?
`

func (q *Queries) DeleteMessage(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMessage, id)
	return err
}

const deleteOldMessages = `-- name: DeleteOldMessages :exec
DELETE FROM messages AS outer_msg
WHERE outer_msg.session_id = ?
AND outer_msg.id NOT IN (
    SELECT inner_msg.id FROM messages AS inner_msg
    WHERE inner_msg.session_id = outer_msg.session_id
    ORDER BY inner_msg.created_at DESC
    LIMIT ?
)
`

type DeleteOldMessagesParams struct {
	SessionID string `json:"session_id"`
	Limit     int64  `json:"limit"`
}

func (q *Queries) DeleteOldMessages(ctx context.Context, arg DeleteOldMessagesParams) error {
	_, err := q.db.ExecContext(ctx, deleteOldMessages, arg.SessionID, arg.Limit)
	return err
}

const deleteSessionMessages = `-- name: DeleteSessionMessages :exec
DELETE FROM messages WHERE session_id = ?
`

func (q *Queries) DeleteSessionMessages(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionMessages, sessionID)
	return err
}

const getMessage = `-- name: GetMessage :one
SELECT id, session_id, role, parts, model, provider, is_summary, created_at, updated_at FROM messages WHERE id = ?
`

func (q *Queries) GetMessage(ctx context.Context, id string) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Parts,
		&i.Model,
		&i.Provider,
		&i.IsSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMessagesFromID = `-- name: GetMessagesFromID :many
SELECT m.id, m.session_id, m.role, m.parts, m.model, m.provider, m.is_summary, m.created_at, m.updated_at FROM messages m
WHERE m.session_id = ? AND m.created_at >= (SELECT m2.created_at FROM messages m2 WHERE m2.id = ?)
ORDER BY m.created_at ASC
`

type GetMessagesFromIDParams struct {
	SessionID string `json:"session_id"`
	ID        string `json:"id"`
}

func (q *Queries) GetMessagesFromID(ctx context.Context, arg GetMessagesFromIDParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesFromID, arg.SessionID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Parts,
			&i.Model,
			&i.Provider,
			&i.IsSummary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionMessages = `-- name: GetSessionMessages :many
SELECT id, session_id, role, parts, model, provider, is_summary, created_at, updated_at FROM messages
WHERE session_id = ?
ORDER BY created_at ASC
`

func (q *Queries) GetSessionMessages(ctx context.Context, sessionID string) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getSessionMessages, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Parts,
			&i.Model,
			&i.Provider,
			&i.IsSummary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionMessagesWithLimit = `-- name: GetSessionMessagesWithLimit :many
SELECT id, session_id, role, parts, model, provider, is_summary, created_at, updated_at FROM messages
WHERE session_id = ?
ORDER BY created_at ASC
LIMIT ?
`

type GetSessionMessagesWithLimitParams struct {
	SessionID string `json:"session_id"`
	Limit     int64  `json:"limit"`
}

func (q *Queries) GetSessionMessagesWithLimit(ctx context.Context, arg GetSessionMessagesWithLimitParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getSessionMessagesWithLimit, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Parts,
			&i.Model,
			&i.Provider,
			&i.IsSummary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSummaryMessage = `-- name: GetSummaryMessage :one
SELECT id, session_id, role, parts, model, provider, is_summary, created_at, updated_at FROM messages
WHERE session_id = ? AND is_summary = 1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetSummaryMessage(ctx context.Context, sessionID string) (Message, error) {
	row := q.db.QueryRowContext(ctx, getSummaryMessage, sessionID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Parts,
		&i.Model,
		&i.Provider,
		&i.IsSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMessageParts = `-- name: UpdateMessageParts :exec
UPDATE messages SET parts = ?, updated_at = ? WHERE id = ?
`

type UpdateMessagePartsParams struct {
	Parts     string `json:"parts"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateMessageParts(ctx context.Context, arg UpdateMessagePartsParams) error {
	_, err := q.db.ExecContext(ctx, updateMessageParts, arg.Parts, arg.UpdatedAt, arg.ID)
	return err
}
