// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type Message struct {
	ID        string         `json:"id"`
	SessionID string         `json:"session_id"`
	Role      string         `json:"role"`
	Parts     string         `json:"parts"`
	Model     sql.NullString `json:"model"`
	Provider  sql.NullString `json:"provider"`
	IsSummary int64          `json:"is_summary"`
	CreatedAt int64          `json:"created_at"`
	UpdatedAt int64          `json:"updated_at"`
}

type Session struct {
	ID               string         `json:"id"`
	Title            string         `json:"title"`
	MessageCount     int64          `json:"message_count"`
	SummaryMessageID sql.NullString `json:"summary_message_id"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
}
