// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountSessionMessages(ctx context.Context, sessionID string) (int64, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DecrementSessionMessageCount(ctx context.Context, arg DecrementSessionMessageCountParams) error
	DeleteMessage(ctx context.Context, id string) error
	DeleteOldMessages(ctx context.Context, arg DeleteOldMessagesParams) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSessionMessages(ctx context.Context, sessionID string) error
	GetMessage(ctx context.Context, id string) (Message, error)
	GetMessagesFromID(ctx context.Context, arg GetMessagesFromIDParams) ([]Message, error)
	GetSession(ctx context.Context, id string) (Session, error)
	GetSessionMessages(ctx context.Context, sessionID string) ([]Message, error)
	GetSessionMessagesWithLimit(ctx context.Context, arg GetSessionMessagesWithLimitParams) ([]Message, error)
	GetSummaryMessage(ctx context.Context, sessionID string) (Message, error)
	ListSessions(ctx context.Context) ([]Session, error)
	ListSessionsWithPreview(ctx context.Context) ([]ListSessionsWithPreviewRow, error)
	SearchSessions(ctx context.Context, dollar_1 sql.NullString) ([]Session, error)
	SearchSessionsWithPreview(ctx context.Context, dollar_1 sql.NullString) ([]SearchSessionsWithPreviewRow, error)
	SetSessionSummary(ctx context.Context, arg SetSessionSummaryParams) error
	UpdateMessageParts(ctx context.Context, arg UpdateMessagePartsParams) error
	UpdateSessionMessageCount(ctx context.Context, arg UpdateSessionMessageCountParams) error
	UpdateSessionTitle(ctx context.Context, arg UpdateSessionTitleParams) error
}

var _ Querier = (*Queries)(nil)
