// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, title, message_count, created_at, updated_at)
VALUES (?, ?, 0, ?, ?)
RETURNING id, title, message_count, summary_message_id, created_at, updated_at
`

type CreateSessionParams struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.Title,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.MessageCount,
		&i.SummaryMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decrementSessionMessageCount = `-- name: DecrementSessionMessageCount :exec
UPDATE sessions SET message_count = CASE WHEN message_count > 0 THEN message_count - 1 ELSE 0 END, updated_at = ? WHERE id = ?
`

type DecrementSessionMessageCountParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) DecrementSessionMessageCount(ctx context.Context, arg DecrementSessionMessageCountParams) error {
	_, err := q.db.ExecContext(ctx, decrementSessionMessageCount, arg.UpdatedAt, arg.ID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, title, message_count, summary_message_id, created_at, updated_at FROM sessions WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.MessageCount,
		&i.SummaryMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT id, title, message_count, summary_message_id, created_at, updated_at FROM sessions ORDER BY updated_at DESC
`

func (q *Queries) ListSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.MessageCount,
			&i.SummaryMessageID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsWithPreview = `-- name: ListSessionsWithPreview :many
SELECT
    s.id,
    s.title,
    s.message_count,
    s.summary_message_id,
    s.created_at,
    s.updated_at,
    COALESCE((SELECT m.parts FROM messages m WHERE m.session_id = s.id AND m.role = 'user' ORDER BY m.created_at ASC LIMIT 1), '') as first_message
FROM sessions s
ORDER BY s.updated_at DESC
`

type ListSessionsWithPreviewRow struct {
	ID               string         `json:"id"`
	Title            string         `json:"title"`
	MessageCount     int64          `json:"message_count"`
	SummaryMessageID sql.NullString `json:"summary_message_id"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
	FirstMessage     interface{}    `json:"first_message"`
}

func (q *Queries) ListSessionsWithPreview(ctx context.Context) ([]ListSessionsWithPreviewRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsWithPreview)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsWithPreviewRow{}
	for rows.Next() {
		var i ListSessionsWithPreviewRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.MessageCount,
			&i.SummaryMessageID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSessions = `-- name: SearchSessions :many
SELECT id, title, message_count, summary_message_id, created_at, updated_at FROM sessions
WHERE title LIKE '%' || ? || '%'
ORDER BY updated_at DESC
`

func (q *Queries) SearchSessions(ctx context.Context, dollar_1 sql.NullString) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, searchSessions, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.MessageCount,
			&i.SummaryMessageID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSessionsWithPreview = `-- name: SearchSessionsWithPreview :many
SELECT
    s.id,
    s.title,
    s.message_count,
    s.summary_message_id,
    s.created_at,
    s.updated_at,
    COALESCE((SELECT m.parts FROM messages m WHERE m.session_id = s.id AND m.role = 'user' ORDER BY m.created_at ASC LIMIT 1), '') as first_message
FROM sessions s
WHERE s.title LIKE '%' || ? || '%'
ORDER BY s.updated_at DESC
`

type SearchSessionsWithPreviewRow struct {
	ID               string         `json:"id"`
	Title            string         `json:"title"`
	MessageCount     int64          `json:"message_count"`
	SummaryMessageID sql.NullString `json:"summary_message_id"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
	FirstMessage     interface{}    `json:"first_message"`
}

func (q *Queries) SearchSessionsWithPreview(ctx context.Context, dollar_1 sql.NullString) ([]SearchSessionsWithPreviewRow, error) {
	rows, err := q.db.QueryContext(ctx, searchSessionsWithPreview, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchSessionsWithPreviewRow{}
	for rows.Next() {
		var i SearchSessionsWithPreviewRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.MessageCount,
			&i.SummaryMessageID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSessionSummary = `-- name: SetSessionSummary :exec
UPDATE sessions SET summary_message_id = ?, updated_at = ? WHERE id = ?
`

type SetSessionSummaryParams struct {
	SummaryMessageID sql.NullString `json:"summary_message_id"`
	UpdatedAt        int64          `json:"updated_at"`
	ID               string         `json:"id"`
}

func (q *Queries) SetSessionSummary(ctx context.Context, arg SetSessionSummaryParams) error {
	_, err := q.db.ExecContext(ctx, setSessionSummary, arg.SummaryMessageID, arg.UpdatedAt, arg.ID)
	return err
}

const updateSessionMessageCount = `-- name: UpdateSessionMessageCount :exec
UPDATE sessions SET message_count = message_count + 1, updated_at = ? WHERE id = ?
`

type UpdateSessionMessageCountParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateSessionMessageCount(ctx context.Context, arg UpdateSessionMessageCountParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionMessageCount, arg.UpdatedAt, arg.ID)
	return err
}

const updateSessionTitle = `-- name: UpdateSessionTitle :exec
UPDATE sessions SET title = ?, updated_at = ? WHERE id = ?
`

type UpdateSessionTitleParams struct {
	Title     string `json:"title"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateSessionTitle(ctx context.Context, arg UpdateSessionTitleParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionTitle, arg.Title, arg.UpdatedAt, arg.ID)
	return err
}
